spring.application.name=yukira-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/yukira
spring.datasource.username=yukira
spring.datasource.password=yukira_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
